# - name: Azure CLI playbook
#   hosts: localhost
#   vars_files:
#     - azure-keyvault/azure-config.yml
#   tasks:
#   - name: Az login with service principal
#     command: 'az login --service-principal -u {{ application_id }} -t {{ tenant_id }} -p {{ client_secret }}'
#     register: user

#   - debug:
#       msg: "user: {{ user.stdout_lines }}"

# - name: Jenkins playbook
#   hosts: jenkins_install_group
#   become: yes
#   roles:
#     - install_jenkins

# - name: Docker playbook
#   hosts: docker_install_group
#   become: yes
#   roles:
#     - install_docker

# - name: GitLab playbook
#   hosts: gitlab_install_group
#   become: yes
#   roles:
#     - install_gitlab

# - name: Nexus playbook
#   hosts: nexus_install_group
#   vars_files:
#     - roles/install_nexus/vars/azurekeyvault_secret.yml
#   become: yes
#   roles:
#     - install_nexus
#   handlers:
#     - import_tasks: roles/install_nexus/handlers/handlers_service.yml

# - name: SonarQube playbook
#   hosts: sonarqube_install_group
#   vars:
#     ansible_python_interpreter: /usr/bin/python3
#   vars_files:
#     - roles/install_sonarqube/vars/azurekeyvault_secret.yml
#     - roles/install_sonarqube/vars/jinja2.yml
#   become: yes
#   roles:
#     - install_sonarqube
#   handlers:
#     - import_tasks: roles/install_sonarqube/handlers/handlers_service.yml

# - name: Nginx playbook
#   hosts: nginx_install_group
#   become: yes
#   roles:
#     - install_nginx
#   handlers:
#     - import_tasks: roles/install_nginx/handlers/handlers_service.yml

# - name: Spring app playbook
#   hosts: springapp_install_group
#   become: yes
#   roles:
#     - install_springapp
#   handlers:
#     - import_tasks: roles/install_springapp/handlers/handlers_service.yml

- name: Provision Jenkins
  hosts: jenkins_provisioning
  vars:
    jenkins_host: "http://139-162-57-40.ip.linodeusercontent.com"
    jenkins_web_user: "admin"
    jenkins_web_password: "123456"
    jenkins_jcasc_config_file: "jenkins/jenkins.yaml.j2"
    jenkins_plugins_file: "jenkins/generate/plugins.yaml"
    jenkins_jobs: "{{ jenkins_jobs }}"
    jenkins_jobs_dir: "jenkins/generate/jobs"
    jenkins_version: 2.414.1
    jenkins_jcasc_version: "1670.v564dc8b_982d0"
  vars_files:
    - "jenkins/generate/list-jobs.yaml"
  roles:
    - ableton.jenkins_jcasc