- name: Main task install Nexus on RedHat
  include_tasks: distro/centos.yml
  when: ansible_os_family == 'RedHat'

- name: Main task install Nexus on Debian
  include_tasks: distro/ubuntu.yml
  when: ansible_os_family == 'Debian'